### ISSUE TITLE
First Draft

### ISSUE THREAD

**Issue by rubabanoyireeta** [heiwot26/Dishwashers#10]
Hi guys, as you know I'm struggling to push my code up to this repository (will ask Greg tomorrow). For now, I've attached a pdf copy of the first draft for someone to look at and maybe start thinking about comments and docstrings.

[draftcodeRN_10112022a.pdf](https://github.com/heiwot26/Dishwashers/files/9984355/draftcodeRN_10112022a.pdf)

**Comment by rubabanoyireeta** [comment]
Update: find the file in my branch, rubabadrafts, and @sksamkumar pull it down from there

**Comment by sksamkumar** [comment]
I'm on it! :)
