### ISSUE TITLE
Code Error

### ISSUE THREAD

**Issue by sksamkumar** [heiwot26/Dishwashers#18]
Line 94: 'unknown file extension encountered'. I have commented on this line so it's easy to spot. This causes the animation not to work.

**Comment by ZJAP024** [comment]
I'll sort this : )

**Comment by ZJAP024** [comment]
So the "unknown file extension encountered" error is due to your personal computer not recognising mp4 as a file type it can write to. On my one I installed ffmpeg from the anaconda site using the anaconda prompt and it was then able to save .mp4 files.
