### ISSUE TITLE
Converting a user input (likely string) into an executable equation

### ISSUE THREAD

**Issue by rubabanoyireeta** [heiwot26/Dishwashers#19]
Hi guys,

I've been research how to take a user input for V(x) and turn it into a function. I got inspo from this forum: https://www.mathworks.com/matlabcentral/answers/121398-how-do-i-convert-a-string-input-to-an-executable-equation

I've got 2 leads, can two of you please look into them? First comment below which one you choose, then comment again with your research when you've finished.

1. inline
<img width="950" alt="inlineexample" src="https://user-images.githubusercontent.com/116881776/201368995-b01a3086-2f21-49b9-826b-3f364dbda787.png">

2. str2func
<img width="454" alt="str2func" src="https://user-images.githubusercontent.com/116881776/201369167-466f5d40-99f7-4ed1-91e0-5008bfb70c78.png">

Thank you!

**Comment by modarwish11** [comment]
ill try str2func

**Comment by heiwot26** [comment]
I will look at inline

**Comment by heiwot26** [comment]
**Inline**
A simple example of how inline is used:

![image](https://user-images.githubusercontent.com/66710136/201386120-2cbc8e87-7397-4934-8799-16719be3f716.png)



From my understanding, the first line should get the string from “handles.edit1” and defines an equation equ.
In our case the first line should be:  equ=get(userpoten,’string’);
Then the second line takes the equ and inline turns it into a function where the independent variable is x.
In our case : f=inline(equ,’x’)

So try:
equ=get(userpoten,’string’);
f=inline(equ,’x’)

however, I do not fully understand inline and believe there are other methods to take an input string and turn it into a usable function. I hope this helps, let me know if this works.

**Comment by heiwot26** [comment]
**eval()**
We may be able to use eval().
Where it can take an input and make it into a variable. So, in our case, the input is userpoten.
We can then define this as:  e=eval(userpoten) 
This may work but im not sure.

**Comment by rubabanoyireeta** [comment]
eval() works like a charm - thanks to both of you for researching these!
