### ISSUE TITLE
Pushing draft code onto repository

### ISSUE THREAD

**Issue by rubabanoyireeta** [heiwot26/Dishwashers#4]
Hi, I'm struggling to push my code up to the repository. Here's what my terminal is saying:

<img width="567" alt="Screenshot 2022-11-09 at 18 05 21" src="https://user-images.githubusercontent.com/116881776/200906472-65c8ff9e-c5bb-4084-98a7-decec10da222.png">

Help!

**Comment by Nergez** [comment]
Have you done git add and git commit before you pushed it up?

**Comment by rubabanoyireeta** [comment]
I tried this!
<img width="692" alt="Screenshot 2022-11-10 at 19 50 52" src="https://user-images.githubusercontent.com/116881776/201192438-d198ab31-ccb4-409f-844a-081a06af547d.png">

**Comment by rubabanoyireeta** [comment]
Nevermind guys, I got help and it worked. draftcodeRN.py is now in the main branch. Hoping to move it to my branch, will keep you updated.
