### ISSUE TITLE
FinDiff

### ISSUE THREAD

**Issue by rubabanoyireeta** [heiwot26/Dishwashers#6]
I like the Method of For Loops to find the finite difference operator - but the task hints that this may be slightly inefficient. Can someone find out what FinDiff does in helping us representing the operator as a matrix for Method 2?

**Comment by modarwish11** [comment]
d2_dx2 = FinDiff(0, dx, 2)
the function FinDiff is very useful for computing many derivatives with great accuracy for many components within a matrix. this code line found in our code, the first parameter decides which axis along the array to take the derivatives, the second parameter dx is the grid spacing and the third is the parameter derivative order you want it in.

**Comment by ZJAP024** [comment]
Yes, we should be using Findiff to act on an array of x-values. If we use the for-loop method, the function we are evaluating the derivative of will be needed to be evaluated 3 different times at each x-value we want, as (f(x - h) - 2 * f(x) + f(x + h)) / h ** 2 will evaluate the function at 3 different points - x-h, x, and x+h. If we want to evaluate a lot of points this becomes extremely bulky to do.
